# Site settings
title: The Wasted Laboratory
description: > # this means to ignore newlines until "baseurl:"
  無駄なゴミ溜め
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xxmogi.github.io" # the base hostname & protocol for your site
twitter_username: xxmogi
github_username:  xxmogi
paginate: 2
paginate_path: "/blog/page:num"
# Build settings
markdown: redcarpet
highlight: none
safe: true
lsi: false
exclude: ['vendor', 'Gemfile', 'Gemfile.lock', '.ruby-version', '.gitignore', '.bundle', '.git', 'LICENSE', 'Flat-UI-master']

gems:
    - jekyll-mentions
#    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
