# Site settings
title: The Wasted Laboratory
description: > # this means to ignore newlines until "baseurl:"
  無駄なゴミ溜め
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xxmogi.github.io" # the base hostname & protocol for your site
twitter_username: xxmogi
github_username:  xxmogi

# Build settings
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
exclude: ['vendor', 'Gemfile', 'Gemfile.lock', '.ruby-version', '.gitignore', '.bundle', '.git', 'LICENSE', 'Flat-UI-master']

gems:
    - jekyll-paginate
